DgBooks/Controllers/AutorController.cs
using DgBooksDetails.DgBServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DgBooks.Controllers
{
    public class AutorController : Controller
    {
        autorServices services = new autorServices();
        personaServices personaServices = new personaServices();
        usuarioServices usuarioServices = new usuarioServices();
        // GET: Autor
        public ActionResult Index()
        {
            return RedirectToAction("index","Home");
        }
        public ActionResult AutorDetail(int id, int idU)
        {
            try
            {
                var autor = services.GetAutor(id);
                int x = int.Parse(autor.idPersona.ToString());
                var persona = personaServices.GetPersona(x);
                var user = usuarioServices.GetUsuarioById(idU);
                ViewBag.Datos = persona;
                ViewBag.Year = persona.dtFechaNacimiento.Year.ToString();
                ViewBag.User = user;
                return View(autor);
            }
            catch
            {
                return RedirectToAction("index");
            }
        }
    }
}

DgBooks/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DgBooksDetails.DgBServices;
using System.Web.Mvc;
using DgBooksDB;
using DgBooks.Models;
using System.Net;
using System.IO;

namespace DgBooks.Controllers
{
    public class LibrosController : Controller
    {
        
        libroServices services = new libroServices();
        usuarioServices usuarioServices = new usuarioServices();
        autorServices autorServices = new autorServices();
        personaServices personaServices = new personaServices();
        generoServises generoServis = new generoServises();

        public LibrosController()
        {
            if (!ValidateSession())
            {
                RedirectToAction("ErrorPage", "Home");
            }
        }

        // GET: Libros
        public ActionResult Index()
        {
            return RedirectToAction("index","Home");
        }
        
        public bool ValidateSession()
        {
            try
            {
                int loginId = MySession.Current.IdUsuario;

                if (loginId == 0)
                {
                    MySession.Current.MensageGeneral = "Es necesario que vuelva ingresar al sistema.";
                    MySession.Current.TipoMensage = "error";
                    //return RedirectToAction("ErrorPage", "Home");
                    return false;
                }
            }
            catch (NullReferenceException Ex)
            {
                MySession.Current.MensageGeneral = "Es necesario que vuelva ingresar al sistema.";
                MySession.Current.TipoMensage = "error";
                //return RedirectToAction("ErrorPage", "Home");
                return false;
            }
            return true;
        }

        [HttpGet]
        public ActionResult PantallaP()
        {
            MySession.Current.MensageGeneral = "";
            MySession.Current.TipoMensage = "";

            try
            {
                if (MySession.Current.Usuario == null) { 
                    if ((int)MySession.Current.IdUsuario > 0)
                    {
                        MySession.Current.Usuario = usuarioServices.GetUsuarioById((int)MySession.Current.IdUsuario);
                    }
                }

                List<Libro> List = new List<Libro>();

                if (Session["IdGenero"] == null)
                {
                    Session["IdGenero"] = 0;
                    List = services.GetLibros();
                }
                else
                {
                    if ((int)Session["IdGenero"] == 0)
                    {
                        List = services.GetLibros();
                    }
                    else
                    {
                        List = services.LibrosGenero((int)Session["IdGenero"]);
                        Session["IdGenero"] = 0;
                    }
                }

                //MySession.Current.Generos = generoServis.GetGeneros();

                List<Models.Genero> generos = new List<Models.Genero>();
                foreach (var item in generoServis.GetGeneros())
                {
                    Models.Genero gen = new Models.Genero();
                    gen.intIdGenero = item.intIdGenero;
                    gen.strNombreGenero = item.strNombreGenero;
                    generos.Add(gen);
                }

                MySession.Current.Generos = generos;

                ViewBag.User = MySession.Current.Usuario;
                return View(List);
            }
            catch(Exception ex)
            {
                string err = ex.Message;
                //return RedirectToAction("LogIn", "Usuario");
                MySession.Current.MensageGeneral = "Error al cargar la ventana principal, intenta nuevamente.";
                MySession.Current.TipoMensage = "error";
                return RedirectToAction("ErrorPage", "Home");
            }
        }

        [HttpPost]
        public ActionResult PantallaP(string intIdLibor)
        {
            MySession.Current.MensageGeneral = "";
            MySession.Current.TipoMensage = "";

            MySession.Current.intIdLibor = Convert.ToInt32(intIdLibor);
            return RedirectToAction("PantallaDetalles", "Libros");
        }

        [HttpPost]
        public ActionResult Busqueda(string inpBusqueda)
        {

            var ListBusqueda = services.GetLibrosBusqueda(inpBusqueda);
            if (ListBusqueda.Count == 0)
            {
                MySession.Current.MensageGeneral = "Sin resultados";
                MySession.Current.TipoMensage = "info";

            }
            else
            {
                MySession.Current.MensageGeneral = "";
                MySession.Current.TipoMensage = "";
            }

            return View(ListBusqueda);
        }
       



        [HttpGet]
        public ActionResult PantallaDetalles()
        {
            try
            {
                int idLibro = (int)MySession.Current.intIdLibor;
                //var user = usuarioServices.GetUsuarioById(idU);
                var libro = services.GetLibroById((int)MySession.Current.intIdLibor);
                var autor = autorServices.GetAutor(int.Parse(libro.intIdAutor.ToString()));
                var persona = personaServices.GetPersona(int.Parse(autor.idPersona.ToString()));
                ViewBag.Autor = persona;
                ViewBag.User = MySession.Current.Usuario;
                ViewBag.Year = int.Parse(libro.dtFechaPublicacion.Value.Year.ToString());
                return View(libro);
            }
            catch (Exception ex)
            {
                MySession.Current.MensageGeneral = "Error al obtener los detalles del libro, intenta nuevamente.";
                MySession.Current.TipoMensage = "error";
                return RedirectToAction("ErrorPage", "Home");
            }
        }

        [HttpGet]
        public ActionResult PantallaLectura(int id, int idU)
        {
            MySession.Current.MensageGeneral = "";
            MySession.Current.TipoMensage = "";

            try
            {
                var libro=services.GetLibroById(id);
                var user = usuarioServices.GetUsuarioById(idU);
                ViewBag.User = user;
                return View(libro);
            }
            catch
            {
                MySession.Current.MensageGeneral = "Error al visualizar el libro, intenta nuevamente.";
                MySession.Current.TipoMensage = "error";
                return RedirectToAction("ErrorPage", "Home");
            }

        }

        public ActionResult Descargar(int id)
        {
            try
            {
                string ruta = @"D:\DgBooks";
                if (!Directory.Exists(ruta))
                {
                    Console.WriteLine("Creando el directorio: {0}", ruta);
                    DirectoryInfo di = Directory.CreateDirectory(ruta);
                }
                var libro = services.GetLibroById(id);
                WebClient mywebClient = new WebClient();
                mywebClient.DownloadFile(libro.strLinkLibro, @"d:\DgBooks\" + libro.NombreLibro+".pdf");
                return RedirectToAction("PantallaDetalles");
            }
            catch
            {
                return RedirectToAction("ErrorPage", "Home");
            }
        }

        #region Favoritos

        [HttpGet]
        public ActionResult PantallaFavoritos()
        {
            try
            {
                var librosFavs = services.LibrosFavs((int)MySession.Current.IdUsuario);
                
                List<Models.Genero> generos = new List<Models.Genero>();
                foreach (var item in generoServis.GetGeneros())
                {
                    Models.Genero gen = new Models.Genero();
                    gen.intIdGenero = item.intIdGenero;
                    gen.strNombreGenero = item.strNombreGenero;
                    generos.Add(gen);
                }

                MySession.Current.Generos = generos;

                if (librosFavs.Count == 0)
                {
                    MySession.Current.MensageGeneral = "Sin registros";
                    MySession.Current.TipoMensage = "info";
                }
                return View(librosFavs);
            }
            catch (Exception ex)
            {
                MySession.Current.MensageGeneral = "Error al visualizar sus favoritos, intenta nuevamente.";
                MySession.Current.TipoMensage = "error";
                return RedirectToAction("ErrorPage", "Home");
            }

        }

        [HttpPost]
        public ActionResult PantallaFavoritos(string intIdLibor)
        {
            MySession.Current.intIdLibor = Convert.ToInt32(intIdLibor);
            return RedirectToAction("PantallaDetalles", "Libros");
        }

        public ActionResult AgregarFavorito(int idLibro)
        {
            try
            {
                var user = usuarioServices.GetUsuarioById((int)MySession.Current.IdUsuario);
                var libro = services.GetLibroById(idLibro);
                var List = services.GetLibros();
                var registro = services.LibroUsuarioAgregar(libro, user);

                MySession.Current.MensageGeneral = "Favorito agregado a su lista.";
                MySession.Current.TipoMensage = "exito";
                return RedirectToAction("PantallaDetalles");
            }
            catch
            {
                MySession.Current.MensageGeneral = "Error al agregar su favorito, intenta nuevamente.";
                MySession.Current.TipoMensage = "error";
                return RedirectToAction("ErrorPage", "Home");
            }
        }

        public ActionResult EliminarFavorito(int idLibro)
        {
            try
            {
                var user = usuarioServices.GetUsuarioById((int)MySession.Current.IdUsuario);

DgBooks/Views/Libros/Busqueda.cshtml
@model IEnumerable<DgBooksDB.Libro>

@{
    ViewBag.Title = "Busqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="wrapper">
    <section class="main-container">
        <div class="location" id="home">
            <h1 id="home">Resultados de la búsqueda</h1>
            <div class="box">

                @if (Model.Count() > 0)
                {
                    foreach (var item in Model)
                    {
                        using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <input type="text" name="intIdLibor" value="@Html.DisplayFor(modelItem => item.intIdLibor)" style="display:none" />

                            <button type="submit" ID="btnAceptar" class="buttons btnCardLibro" name="btnIs" value="Iniciar Sesión" onclick="btnAgregar_Click">
                                <img src="@Html.DisplayFor(modelItem => item.strLinkImagenLibro)"
                                     width="210" height="300" alt="Galeria CSS 1" />
                                <div>
                                    <h3 class="titulo-libro">@Html.DisplayFor(modelItem => item.NombreLibro)</h3>
                                </div>
                            </button>
                        }
                    }
                }
            </div>
        </div>
    </section>
</div>

DgBooks/Views/Libros/PantallaDetalles.cshtml
@model DgBooksDB.Libro

@{
    ViewBag.UserAux = ViewBag.User;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

@*<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>DgBooks</title>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Open+Sans:wght@400;600&display=swap"
              rel="stylesheet">
        <link href="~/css/home.css" rel="stylesheet" />
        <link href="~/css/pantallla.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    </head>
    <body>*@
<div class="wrapper">
    <main>
        <div class="libro-principal">
            <div class="contenedor">
                <div class="row  mt-5">
                    <div class="col-8">
                        <h3 class="titulo"> @Html.DisplayFor(model => model.NombreLibro)</h3>
                        <nav>
                            <p class="autor"><i class="fas fa-users"> @ViewBag.Autor.strNombrePersona @ViewBag.Autor.strApellidoP</i></p>
                            <p class="fecha"><i class="fas fa-calendar"></i> @ViewBag.Year</p>
                        </nav>

                        <p class="descripcion">
                            @Html.DisplayFor(model => model.strSinopsis)
                        </p>

                        <a href="@Url.Action("PantallaLectura", new { id=Html.DisplayFor(model=>model.intIdLibor), idU=ViewBag.User.intIdUsuario})">
                            <button role="button" class="boton"><i class="fas fa-book-open"></i> Leer</button>
                        </a>

                        @*<button role="button" class="boton"><i class="fas fa-heart"></i>Favorito</button>*@
                        <a href="@Url.Action("AgregarFavorito","Libros", new { idLibro=Html.DisplayFor(model=>model.intIdLibor)})">
                            <button role="button" class="boton"><i class="fas fa-heart"></i></button>
                        </a>

                        <a href="@Url.Action("AutorDetail","Autor", new { id=Html.DisplayFor(model=>model.intIdAutor), idU=ViewBag.User.intIdUsuario})">
                            <button role="button" class="boton"><i class="fas fa-info-circle"></i>Más información</button>
                        </a>

                        <a href="@Url.Action("Descargar","Libros", new { id=Html.DisplayFor(model=>model.intIdLibor)})">
                            <button role="button" class="boton"><i class="fas fa-info-circle"></i>Descargar</button>
                        </a>
                    </div>

                    <div class="col-2">
                        <div class="card">
                            <img src="@Html.DisplayFor(model => model.strLinkImagenLibro)" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

<script src="https://kit.fontawesome.com/2c36e9b7b1.js" crossorigin="anonymous"></script>

@*</body>
</html>*@

DgBooks/Views/Libros/PantallaFavoritos.cshtml
@model IEnumerable<DgBooksDB.Libro>

@{
    ViewBag.Title = "PantallaFavoritos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="wrapper">
    <section class="main-container">
        <div class="location" id="home">
            <h2 class="titulo-seccion">Mis favoritos</h2>
            <div class="box">

                @if (Model.Count() > 0)
                {
                    foreach (var item in Model)
                    {
                        using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <a href="@Url.Action("EliminarFavorito","Libros", new { idLibro = item.intIdLibor })" class="link-action-icon">
                                <button role="button" class="boton btn-action-icon"><i class="fas fa-heart-broken"></i></button>
                            </a>

                            <input type="text" name="intIdLibor" value="@Html.DisplayFor(modelItem => item.intIdLibor)" style="display:none" />

                            <button type="submit" ID="btnAceptar" class="buttons btnCardLibro" name="btnIs" value="Iniciar Sesión" onclick="btnAgregar_Click">
                                <img src="@Html.DisplayFor(modelItem => item.strLinkImagenLibro)"
                                     width="210" height="300" alt="Galeria CSS 1" />
                                <div>
                                    <h3 class="titulo-libro">@Html.DisplayFor(modelItem => item.NombreLibro)</h3>
                                </div>
                            </button>

                        }
                    }
                }
            </div>
        </div>
    </section>
</div>


@*@if (Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreLibro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.strLinkImagenLibro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.strLinkLibro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.strSinopsis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor.strLinkFoto)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreLibro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.strLinkImagenLibro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.strLinkLibro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.strSinopsis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Extencion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.strLinkImagenLibro)

                </td>
                <td>
                    @Html.ActionLink("Eliminar", "EliminarFaborito")
                </td>
            </tr>
        }
    </table>
}*@

DgBooks/Views/Libros/PantallaLectura.cshtml
@model DgBooksDB.Libro

@{
    ViewBag.UserAux = ViewBag.User;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Open+Sans:wght@400;600&display=swap"
          rel="stylesheet">
    <link href="~/css/home.css" rel="stylesheet" />
    <link href="~/css/pantallla.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>DgBooks</title>
</head>
<body>*@
    <main>
        <embed src="@Html.DisplayFor(model => model.strLinkLibro)" type="application/pdf" height="900" width="2100" />
    </main>

    <script src="https://kit.fontawesome.com/2c36e9b7b1.js" crossorigin="anonymous"></script>
@*</body>
</html>*@

DgBooks/Views/Libros/PantallaP.cshtml
@model IEnumerable<DgBooksDB.Libro>

@{
    ViewBag.UserAux = ViewBag.User;
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@*<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Inicio</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js" integrity="sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9" crossorigin="anonymous"></script>
    <link href="~/css/pantallla.css" rel="stylesheet" />

</head>
<body>*@
    <div class="wrapper">
        <section class="main-container">
            <div class="location" id="home">
                <h1 id="home">Popular en DgBook's'</h1>
                <div class="box">

                    @if (Model.Count() > 0)
                    {
                        foreach (var item in Model)
                        {
                            using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <input type="text" name="intIdLibor" value="@Html.DisplayFor(modelItem => item.intIdLibor)" style="display:none" />

                                <button type="submit" ID="btnAceptar" class="buttons btnCardLibro" name="btnIs" value="Iniciar Sesión" onclick="btnAgregar_Click">
                                    <img src="@Html.DisplayFor(modelItem => item.strLinkImagenLibro)"
                                         width="210" height="300" alt="Galeria CSS 1" />
                                    <div>
                                        <h3 class="titulo-libro">@Html.DisplayFor(modelItem => item.NombreLibro)</h3>
                                    </div>
                                </button>
                            }
                        }
                    }

                </div>
            </div>
        </section>
    </div>
@*</body>
</html>*@